---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-dnsdist

        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542

        containers:
          main:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.2@sha256:ab8cc91bcf93d2a147767032d37c52ca2528439d037090657a18ea39cfeb272b
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
            resources:
              requests:
                cpu: 49m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 568
              runAsGroup: 568

          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.2

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest@sha256:c8f61c8ecaa86e66b7afd53517a3530082ed4bb8697601ff251bbbff3f7f9f9c
            env:
              - name: VPN_SERVICE_PROVIDER
                value: "mullvad"
              - name: VPN_TYPE
                value: "wireguard"
              - name: VPN_INTERFACE
                value: "wg0"
              - name: VPN_ENDPOINT_PORT
                value: "51820"
              - name: VPN_PORT_FORWARDING
                value: "on"
              - name: WIREGUARD_PRIVATE_KEY
                value: "4C0SO7FIA4t54FQqHmRW30LeyHmG1SrlN67HoQYgfHM="
              - name: WIREGUARD_ADDRESSES
                value: "10.66.43.63/32"
              - name: VPN_PORT_FORWARDING_PROVIDER
                value: "protonvpn"
              - name: FIREWALL_INPUT_PORTS
                value: "8080"
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: DNS_PLAINTEXT_ADDRESS
                value: "127.0.0.2"
            # envFrom:
            #   - secretRef:
            #       name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          port-forward:
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      dnsdist-config:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          main:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
      config:
        type: emptyDir
        enabled: true
