apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:UaFm23flQNbbadaoddQv1jPS/6xE7clisIQcWyVukZEHXeN2BNBfYQ==,iv:U+jUkGDdfSFA1UzfiNJGu7TUa4NWsXDcxbxHx3uVMNc=,tag:nilhHrlRfwvJeTYYFBwCUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xysqy8j5r8n8yauxdq7ys844ty06ygcfg20tcjlsg58y44rlpuqpwcvnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSTdLcHNGbkZtVWpOZ1JJ
            Rk9NZHMxSExGNXdNM3pTL05zRjhXaEs3SzA4Ck5Pb1orVWlIRHJFL2s5OHVqZGti
            enNqcCtUaVJIY3I4ZWVOa2NNTDlpalEKLS0tIEM5aC9YaUhyUmVhZGcrMUREYkFl
            VHFjbkRROHYzdkZUeUNsS0RWMzdUak0KvJCLQfVubLrjY1hsX7vy1v7G34GvSv5k
            yiVnJ/u4/XknxM5u5pqGBp+nNGZ+1gDnXNkewqy5pXgBHL7NHDe/IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T13:47:37Z"
    mac: ENC[AES256_GCM,data:zoum1sF0zS+ld4JPMt2QKuXqMlSx33bm2DiAZg7RAC5+jItWTlC+7fhMOsRyh2wv7hE4lEoh1eJktzQQ9a+l1MN4zPhYH12SF5ruiSe9sGBLrH9G771zuEq5OMn/AzC2gssUTYIK43CHRNYK3cT1zmzl7iUDYrtXyi9rqe8pYso=,iv:DmOWQdL1zn4oYui0rx7wUWxAqmFmSaMHstPqzn0yt+E=,tag:LNqhWRqDfsfSrTQ5yV2CmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
