ansible_become_pass: ENC[AES256_GCM,data:mfUce7Kieg==,iv:/kXRCxfEqmn1fh4A79Y4P1rURhWyggYs99zut85gNrU=,tag:kX91hjdz8UD+0ZPcLi5KCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xysqy8j5r8n8yauxdq7ys844ty06ygcfg20tcjlsg58y44rlpuqpwcvnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b0FTaUd3bERhUWd6K2U0
            Mng5RXMwWHFsN083b3l4U1QxY0dBMWc4c2lJCmdvVGRWbENJQW1JR1lxTmxSSUZk
            eEE4aXhyR1pWL2VGS3NDMEplNkhpUTAKLS0tIFpaSnJ2QUNnUm45WjFXVlVMa2wz
            VWRyQlh6OWIvMFFCYmlNUUtaeGpNN3MKur5uVO2HlVPvwFzh60GlJHjBNL+h1PiZ
            e7aft0Jed8R/rxTYrwFS6WVpwVNuydppYVy7TMdYUAqcjxbnnJhGcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T13:46:11Z"
    mac: ENC[AES256_GCM,data:m1Q02gLYkPtJC3u+CfWBUvsRXTis5BBaFZBwuAcxDiVpHWd1dOerDsLGTxU6TprQrBdX/JiRjRaJ6FB3StDI4FWBEIKuDsbkVxKbo2C1PRT1nrEICnEyrQfFWCaRyDnOUHIM2cSdnub/3ZOmd9AeiuVtWBSQVwZPQr19yjZcMko=,iv:6fDSeSUxO3KW3uBsy5+qYg+gs2dfJN8Fko6N0qAukVY=,tag:Jm0NIcleVaF/b/UyG5aJvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
