ansible_become_pass: ENC[AES256_GCM,data:x/uaEMhHMw==,iv:9eLtOrNmxAEgBKsijOI+jLGoQYx9oHi3k7+M1Qtr1OY=,tag:WuYWl/ec3BXQgIx8Mi8BTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xysqy8j5r8n8yauxdq7ys844ty06ygcfg20tcjlsg58y44rlpuqpwcvnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZGNHSThGdWtNL0RON0Iy
            L292UE0yazd0TkFFMWpRMFp0bTRkUWhoMlVBCjBaNkw0Rjh2b3U2VzBIbG02NlJ0
            SlJsbFoyQjFRTGdTdUY2KzFjUnROZmcKLS0tIFJISUNoSEJabXpTNVJSY053cUth
            QTBkYWNnODJZWlNPM1R5SFBibWJadVEKCLLPFFuY/3ciKRkle3jMpEykl1fq3HSd
            +1/43keXKMWhBr8AA5nXYwLNf0sN54Cww48wbVaSlt+mXNJGT0/ToQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T19:38:22Z"
    mac: ENC[AES256_GCM,data:zredeJk1YAwCgO9j3LXAI7wab90QO7pGPyTQLm8BsBTKDr4M/yHhvf6Vy2HMDGRlDvFSk1CuVMPL6Zd36QAUySr98K0CHxJGIUn/v10zQx4yXq9KvxXp+wpgi7GtGiQsSTia1T5vN0/ELE5F5SGF6rAZp7wMz0K/2MBAAPmVEDc=,iv:bd+XJu7DTV66uxTj5FCckklzu6SRAvgewtcvWN4ySIM=,tag:HZqOtQi2oukUDyDC2b2F+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
