apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5dIMp44fnpOG6ax2TNgbBgEq7Amo517ZKfSg9k4R2uuIfYjIcI3uVg==,iv:HebNtYWUXENMHv+Kpq5gbBoKhd1XbsDUljytbkd6WTw=,tag:LmWKJ5asdGVmyQIWKEfqGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19qxwmklm0dhnkd0hwewd4f2j0r4yn0mzlu8j5a7v06qktk9pd5msvsqr8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVm96V3huaFhBZjFoYVoy
            bTQrSVY2S0plZFFpWlA3Sjd0d1U0dkxrNFM0CkNiWGFNQ1UzSWpRV0ZkdHhia3pY
            clBwRnZIK3hHa21oZkxMN1YvdExEODQKLS0tIDFmM3lHblRYVXF4TWhxdTZ0ckg4
            aXJiWmgzNUdaZWJGRm5ISHNvSHhVTkkKfIctC6YAnJPpkSlmswQXgDa+qWYFsA39
            lqLCXrrrazL6jEmA/gXVYQDbeKIvTwcENRAfSVlmUnuXroc892ln2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T22:15:32Z"
    mac: ENC[AES256_GCM,data:AWh3eor5XAxISqxuuZ+lIN9bCK3POd0h/KdAyLTKH8LjH1Vnl8xO+Kp4l+X9Yn2gugmfJB7QnctrZDqAY9fnZ0nJ2O82fzgA1cyDKgsqN9aVFBjVv874l0HUqb5OXJBOxZit8RNxGLwM5mTqn7T9//QJyaGluwnqnNEb860LR2Y=,iv:9xg2bqxqJHr6lmrwHuoYgBWxc4fEE7LukbqZPna7rAU=,tag:+VV4XXmO/B8gPWXdPR3lvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
