apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+xnQuPDt9M+kZgx46lOigEN0ysSD0kJobIPR317ZaCNZ6oP3Yin56w==,iv:/JiVsPccOHafkz7Upv+9da9EcKuyCz5p4WR2Z6mmQJ8=,tag:Li6UrGUFEUE5Dt/EVvUAjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xysqy8j5r8n8yauxdq7ys844ty06ygcfg20tcjlsg58y44rlpuqpwcvnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ2tRYnR6Z01lTVVXdXJ1
            bWMyMSsvbDNhNHB5Ymkrb3U3dDVaelZBY1hJCnFmN0xxOVBzbCtLOU96ZEFCbG5Z
            TjRMOVZ5ZXgwaHVsWS9yTWdBUEhpdEEKLS0tIGRRS1VSeWtObTJIUWFKNzYwTXdW
            OGVweUNNb3p1MzhBZnRwdFZkK0lMWDgKr6OuKpBnYuq5OIU5565RKiYa4E4dOLFm
            85yDgWlJ9wlEVeUKXbaW0zhTXdEKP5pFt0fQyzKa+N26zhGK6TWVOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T13:47:36Z"
    mac: ENC[AES256_GCM,data:6jmXat9ctLJTKHxM3Gl+uaTOD1zA65MSPxU4u7OYOymPWfw3t5Ns9TVUPkwujREz4AafcjzYxgsGduFwvxbtOxnyuGXcKL3d9ViVq31oYImv+MemTwopxUITDMLsGyu1tl3a2Rp5wh5J1brTWk4EVLqP3gQ122B1OQA6eOPwea0=,iv:HoeKMUamdUq7taKPmjHkOyQnxs7zLiESTjn5sQ4IYl0=,tag:GEHSpVFzyNlNGtRQNpO+lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
