apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zzhlCCAUsSPZ3TG0gNzvnb6ifBq+TJE=,iv:mx3T97izW5yw88K+do24DMuXbTG+3m9pk28a8WO8/No=,tag:q0OYRPtiE/HPfV98aA79yw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mHPMbcV4e7ds4D0QfJ6mi9kVyF1xkPrF6BOpxWKZzDaj8jbF,iv:ZZgLAIggR9qQgWA2f/Scb+RL9CU//ycj6f1Qz+OL4bo=,tag:2kcNN+XYL2rQGC42wPmRng==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZZc7oWEeUZg=,iv:AnqKyIpKXZzYlqQv1lqPraWJKMphWHmsLGW4ANpztZk=,tag:cbvlYZavrqsyS525r0FiKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xysqy8j5r8n8yauxdq7ys844ty06ygcfg20tcjlsg58y44rlpuqpwcvnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSG9RNmVvZHQ2dE5zQWM4
            cVAxaXQ4elA1UjFjNnp3WG95Y2J6MHVTZVEwCmJ1T2JURXVlYkwzV09WcUVqcCtW
            Tm1jeGZXa3ZLM0VZZ3NsVXVJaS83bmMKLS0tIEpNcXM5ZUg5blhBZlNpemFUb2ps
            Rm4ybm1uSGlsVGZ2VzNKbmNsWWh6REkKrgKAkw35HDdJ7LEUpeGbWL+UUquN9kVC
            CjaMAiauMDAnQv3mf01JUZHwTy7Dj4vuP1yeCJC8ZxsvRXAigbL6kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T19:39:52Z"
    mac: ENC[AES256_GCM,data:IZQKkAlLUU82hcjEPfS7gB0g6GWaKQblMgGsMYkqA0sBHNdFmHrC1Mc0UR8OEtmcuOdH02VtcySqy0RptPJO6mAkzrOyT4+LKujqrZ1N7YJNY4lT+WJ5Cu28cnjJOPMVxIORAf374amVS2zVly4ILqcEwqzB/rjNJx7nUMq7SAA=,iv:YBKUT1De/Ixr2Gq8YC4mAxtQWPedrDXFwqplAsqT4b8=,tag:t11he4U7h/vo/sUPHNNqTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
